codecov:
  require_ci_to_pass: yes
  token: e1a7d1ce-c45e-4d57-9712-8b080935512a

coverage:
  precision: 2
  round: down
  range: "70...100"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

# comment:
#   layout: "reach,diff,flags,files,footer"
#   behavior: default
#   require_changes: no


comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false  # if true: only post the comment if coverage changes
  require_base: no        # [yes :: must have a base report to post]
  require_head: yes       # [yes :: must have a head report to post]
  branches:               # branch names that can post comment
    - "main"
    - "backend-sprint2"
    - "test-final"
    - "last_minute_features"