name: subfolder
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Print versions
        run: |
          which npm
          npm --version
          which yarn
          yarn --version

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
            
      - name: Install modules
        run: npm install --prefix source/site
        
      # - name: Cypress install
      #   uses: cypress-io/github-action@v2
      #   with:
      #     runTests: false
      #     working-directory: source/site

      - name: Start server
        run: cd source/site && npx yarn start-server &

      # - name: Generate Jsdocs
      #   run: cd source/site && npx yarn docs    

      # - name: Run all tests
      #   run: cd source/site && npx yarn coverage
      # - name: Commit coverage files
      #   run: |
      #     git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
      #     git config --local user.name "github-actions[bot]"
      #     git add .source/coverage
      #     git commit -m "generated coverage"

      # - name: Push changes
      #   uses: ad-m/github-push-action@master
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     branch: ${{ github.ref }}    


      - name: Run all tests
        run: cd source/site && npx yarn coverage:jest


      - name: Upload coverage to Codecov
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          directory: ./source/site/coverage/jest-coverage
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)

      # # now run the tests from the subfolder
      # - name: Cypress run
      #   uses: cypress-io/github-action@v2
      #   with:
      #     install: false
      #     working-directory: source/site
      #     start: yarn start-server