name: subfolder
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Print versions
        run: |
          which npm
          npm --version
          which yarn
          yarn --version

      - name: Install modules
        run: npm install --prefix source/site
        
      - name: Cypress install
        uses: cypress-io/github-action@v2
        with:
          runTests: false

      # now run the tests from the subfolder
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          install: false
          working-directory: source/site
          start: yarn start-server