name: subfolder
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Print versions
        run: |
          which npm
          npm --version
          which yarn
          yarn --version

      - name: Install modules
        run: npm install --prefix source/site
        
      - name: Cypress install
        uses: cypress-io/github-action@v2
        with:
          runTests: false
          working-directory: source/site

      - name: Install modules
        run: cd source/site && npx yarn start-server &

      - name: Run Cypress tests
        run: cd source/site && npx yarn coverage    

      - name: Codecov
        run: cd source/site && bash <(curl -s https://codecov.io/bash)  

      # # now run the tests from the subfolder
      # - name: Cypress run
      #   uses: cypress-io/github-action@v2
      #   with:
      #     install: false
      #     working-directory: source/site
      #     start: yarn start-server