name: jest
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm install --prefix source/site
    - name: Run tests
      run: npm --prefix source/site test