on: push

jobs:
  run-linters:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Run ESLint
      run: eslint source/site/**/ --ext .js,.jsx,.ts,.tsx
