name: lint-css
on: [push]

jobs:
  linters:
    name: stylelint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions-hub/stylelint@master
        ENV:
          PATTERN: "*.css"
          INDENT_SPACES: 4