name: test-coverage
on: push

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: test-coverage
        uses: raulanatol/jest-coverage-comment-action@v1.0.4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: 'source/site'