name: tests_and_docs
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Print versions
        run: |
          which npm
          npm --version
          which yarn
          yarn --version

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install modules
        run: npm install --prefix source/site

      - name: Start server
        run: cd source/site && npx yarn start-server &

##### Testing Section ####
      - name: Run all tests
        run: cd source/site && npx yarn coverage
        
      - name: Commit coverage files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add --force source/coverage
          git commit -m "generated coverage"

##### Jsdocs Section ####

      - name: Swap directory
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: JSDoc Action
        uses: andstor/jsdoc-action@v1.2.0
        with:
          source_dir: ./source/site/frontend/js
          recurse: true
          output_dir: ./docs
      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add docs
          git commit -m "generated jsdocs"

#### Push to repo ####
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}    

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          directory: ./source/coverage/merged
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)