name: test-coverage
on: push

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: test-coverage
        uses: mattallty/jest-github-action@v1.0.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          working-directory: "/home/runner/work/cse110-w21-group17/cse110-w21-group17/source/site"
          test-command: "npm test --prefix /home/runner/work/cse110-w21-group17/cse110-w21-group17/source/site"